### ISSUE TITLE
Update Sticky Footer 10/15

### ISSUE THREAD

**Issue by maxram7** [jiwoochun/sailpointwp#13]
Hi there,
When I let you know it's ok to do so, will you swap out "Navigate '17" in the sticky footer with "What’s Your Identity Score?" and link to: https://www.sailpoint.com/identity-management-risk-assessment/

If we can't get that to fit, we can shorten to "Identity Score Survey" but the longer is preferred. If everything is ok I'll ping you to swap it out on Monday sometime.

**Comment by maxram7** [comment]
@sharpsays can you add the tracking code for the url here for Jiwoo?

**Comment by sharpsays** [comment]
@jiwoochun Here is the url to plug in on the footer:
/identity-management-risk-assessment/?elqct=Website&elqchannel=Footer

**Comment by jiwoochun** [comment]
Updated but the css isn't showing up because of the caching issue. Will report back  here and close this issue once I see it updated.

**Comment by jiwoochun** [comment]
Completed.
