### ISSUE TITLE
Blog/Resource?

### ISSUE THREAD

**Issue by sharpsays** [jiwoochun/sailpointwp#23]
@jiwoochun I've found a blog post that has a landing page stuck to the top of it. Not sure how it happened, but hoping there is an easy fix for it. https://www.sailpoint.com/blog/cloud-identity-governance/

**Comment by jiwoochun** [comment]
@sharpsays 
I've been trying to find this blog post for too long... I give up! Do you know what the title of it is? it says it's a resource but it's under the 'blog' directory. The page `/resources/cloud-identity-governance/` looks like it's the correct but I'm not sure how this exists in the `blog` directory. Any help would be appreciated!

**Comment by sharpsays** [comment]
@jiwoochun Yeah...this one took me a while to wrap my head around. I found it via a broken link checker. If you use /resources/cloud-identity-governance it will show the landing page only. If you type in /blog/cloud-identity-governance it will show the landing page on top and the blog post on bottom. It should only be showing the blog post. I have no idea where the landing page is coming from. I finally found the blog post in WordPress. Turns out you can search the text of the blog post in the Posts section (I wish I'd known that earlier). Anyways, here is the title, 'Identity in the Cloud: 3 Reasons You Can Do It Now.'

**Comment by jiwoochun** [comment]
@sharpsays 
Thanks for pointing me in the right direction. This is a really really weird issue but it looks like it's breaking because the permalinks are identical even tho they're technically in different "directories". 

For now the temporary fix was to change the permalink to something other than `cloud-identity-governance` and do a redirect to it.

**Comment by sharpsays** [comment]
@jiwoochun  Thanks!
