### ISSUE TITLE
Consolidating header.php

### ISSUE THREAD

**Issue by jiwoochun** [jiwoochun/sailpointwp#3]
Consolidate all headers on .com to be uniform, make sure tracking is still working for demo button

**Comment by maxram7** [comment]
Did we fix all the headers to not open in a new window? I thought so, but found this page that opens the .com site in a new window when you click on the logo: https://www.sailpoint.com/identity-management-and-governance-leader-forrester-wave/

**Comment by jiwoochun** [comment]
Answer: No.

We didn't fix every page yet (obviously). The page you linked is the first time I've seen that page. I'll take a look at it.

**Comment by jiwoochun** [comment]
Header fixed for page:
https://www.sailpoint.com/identity-management-and-governance-leader-forrester-wave/

Still looking into consolidating all headers without breaking the site.

**Comment by jiwoochun** [comment]
I think I found out the problem. There's a script that is firing for resource pages that loads jQuery mobile. There's some weird interference with this file. I have tested this by turning off this script and the homepage loads fine. I will need to investigate if this is something we actually use/need before turning it off on the live site.

**Comment by maxram7** [comment]
Ah, good sleuth work.

**Comment by jiwoochun** [comment]
- Going ahead with deactivating jquery mobile from `custom-scripts.php`. This takes care of homepage logo link error.
- Default header reinstated for `resource` post-type pages (menu and demo are now available).
- Footer is also rendering on `resource` post-type pages (not sticky footer).
